# Generated by Django 4.1.4 on 2025-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_blog_thumbnail_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="docs_images/"),
                ),
            ],
        ),
    ]
